figlet "Diana Starter Dotfiles"
echo "Comming soon"
echo "Downloading dotfiles"
echo "Installing dotfiles dependencies"
echo "Installing dotfiles"
echo "Do you want to use the desktop or laptop configuration"
echo "Downloading wallpaper"
echo "Installing wallpaper"
echo "Setting up greetd"
echo "Switching shell to zsh"
